---
- hosts: localhost

  tasks:
  - name: check for existence of ~/.ansible/jupyterhub-secrets.yml
    ansible.builtin.stat:
      path: ~/.ansible/jupyterhub-secrets.yml
    register: secrets_file

  - name: check for existence of ~/.ansible/vaultpassword
    ansible.builtin.stat:
      path: ~/.ansible/vaultpassword
    register: password_file

  - name: create secret file
    block:
    - name: create random string and save it in pg_password
      ansible.builtin.set_fact:
        pg_password: "{{ lookup('community.general.random_string', special=true, override_special='_-#+*', length=20, min_special=1, ignore_similar_chars=true) }}"
    - name: display postgres password
      ansible.builtin.debug:
        msg: "pg_password: {{ pg_password }}"
  
    - name: Pausing for Github Org owner id
      ansible.builtin.pause:
        prompt: Github Org owner id
      register: gh_org_owner_name_prompt
      no_log: true
    - ansible.builtin.set_fact:
        gh_org_owner_name: "{{ gh_org_owner_name_prompt.user_input }}"
    - name: display Github Org owner id
      ansible.builtin.debug:
        msg: "gh_org_owner_name: {{ gh_org_owner_name }}"

    - name: Pausing for Github client id
      ansible.builtin.pause:
        prompt: Github client id
      register: gh_client_id_prompt
      no_log: true
    - ansible.builtin.set_fact:
        gh_client_id: "{{ gh_client_id_prompt.user_input }}"
    - name: display Github client id
      ansible.builtin.debug:
        msg: "gh_client_id: {{ gh_client_id }}"
  
    - name: Pausing for Github client secret
      ansible.builtin.pause:
        prompt: Github client secret
      register: gh_client_secret_prompt
      no_log: true
    - ansible.builtin.set_fact:
        gh_client_secret: "{{ gh_client_secret_prompt.user_input }}"
    - name: display Github client secret
      ansible.builtin.debug:
        msg: "gh_client_secret: {{ gh_client_secret }}"
  
    - name: Pausing for Github OAuth callback url
      ansible.builtin.pause:
        prompt: Github OAuth callback url
      register: gh_oauth_callback_url_prompt
      no_log: true
    - ansible.builtin.set_fact:
        gh_oauth_callback_url: "{{ gh_oauth_callback_url_prompt.user_input }}"
    - name: display Github client callback url
      ansible.builtin.debug:
        msg: "gh_oauth_callback_url: {{ gh_oauth_callback_url }}"

    - name: create jupyterhub-secrets variable file in ~/.ansible on control node
      ansible.builtin.template:
        src: jupyterhub-secrets.yml.j2
        dest: ~/.ansible/jupyterhub-secrets.yml
        mode: '0600'
    when: not secrets_file.stat.exists

  - name: create default ansible vault password file (~/.ansible/vaultpassword) with correct permissons
    ansible.builtin.copy:
      dest: ~/.ansible/vaultpassword
      mode: '0600'
      content: |
        ***IMPORTANT***: Replace the contents of this line (no newline) with your ansible vault password in plaintext
    when: not password_file.stat.exists
