---
- hosts: "{{ target_hosts | default('all') }}"
  gather_facts: true
  become: true
  vars:
    nginx_reverse_proxy_app: jupyterhub
    nginx_reverse_proxy_app_listen_port: 8000
    sysacct_name: jupyterhub
    sysacct_uid: 978
  roles:
  - almalinux-8-base
  - podman-systemd
  - jupyterhub-podman-systemd
  - nginx-reverse-proxy